routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'login', 'middleware' => 'guest', 'uses' => '\App\Http\Controllers\HomeController@index']);
Route::post('/do-login', ['as' => 'do-login', 'uses' => '\App\Http\Controllers\HomeController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => '\App\Http\Controllers\HomeController@logout']);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {

    Route::get('/', ['as' => 'dashboard', 'uses' => '\App\Http\Controllers\backend\DashboardController@index']);

    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/list', ['as' => 'list', 'uses' => '\App\Http\Controllers\backend\UserController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => '\App\Http\Controllers\backend\UserController@store']);
    });

    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/list', ['as' => 'list', 'uses' => '\App\Http\Controllers\backend\RoleController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\RoleController@create']);
    });

    Route::group(['prefix' => 'master-data', 'as' => 'master-data.'], function () {
        Route::get('/', ['uses' => '\App\Http\Controllers\backend\MasterDataController@indexKategori']);
        Route::get('/ajax-category', ['as' => 'ajax-category' , 'uses' => '\App\Http\Controllers\backend\MasterDataController@ajaxKategori']);
        Route::post('/store-kategori', ['as' => 'store-kategori', 'uses' => '\App\Http\Controllers\backend\MasterDataController@storeKategori']);
        Route::post('/store-sub-kategori', ['as' => 'store-sub-kategori', 'uses' => '\App\Http\Controllers\backend\MasterDataController@storeSubKategori']);

    });

      Route::group(['prefix' => 'data', 'as' => 'data.'], function () {
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\DashboardController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => '\App\Http\Controllers\backend\DashboardController@store']);

    });

});

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Repositories\KategoriRepository;
use App\Http\Repositories\TidRepository;
use App\Http\Repositories\SubKategoryRepository;
use Illuminate\Http\Request;
use Auth;

class DashboardController extends Controller
{

	protected $kategori;

	protected $subKategori;

    protected $tid;

	public function __construct(KategoriRepository $kategori, SubKategoryRepository $subKategori, TidRepository $tid)
	{
		$this->kategori = $kategori;
		$this->subKategori = $subKategori;
        $this->tid = $tid;

	}


    public function index(Request $request)
    {
        $data = $request->all();
    	$subKategoris = $this->subKategori->getData();
        $checklist = $this->tid->getData($data);
        return view('backend.data.index', compact('subKategoris','checklist'));
    }


    public function create()
    {

        $tid = $this->createTID();
    	$subKategoris = $this->subKategori->getData();
        return view('backend.data.create', compact('subKategoris','tid'));
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $dataTid = array('tid_id' => $data['tid'], 'id_user' => Auth::user()->id, 'keterangan' => $data['keterangan']);
        $tid =  $this->tid->store($dataTid);
        $subKategoris = $this->subKategori->getData();
        foreach($subKategoris as $i => $row) { 
            $a = array_search($row->id, $data['id_sub_kategori'] ?? []);
            if ( ( $data['id_sub_kategori'][$a] ?? '' ) == $row->id ) {
                $data_checklist[] = array(
                        'id_sub_kategori' =>  $row->id ,
                        'status' => 1, 
                        'id_tid' => $tid->id,
                        'kode_tid' => $data['tid']
                       
                    ); 
            }else{
                $data_checklist[] = array(
                        'id_sub_kategori' =>  $row->id ,
                        'status' => 0, 
                        'id_tid' => $tid->id,
                        'kode_tid' => $data['tid'],
                    );
            }
        }

        $tid->checklist()->createMany($data_checklist);
        return redirect(route('admin.dashboard'));
    }


    public function createTID()
    {
         $userId = Auth::user()->id;
         return $tid = 'PID-'.$userId.'-'.date('dmis');
    }
}

app/Http/Controllers/backend/MasterDataController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Repositories\KategoriRepository;
use App\Http\Repositories\SubKategoryRepository;
use Illuminate\Http\Request;

class MasterDataController extends Controller
{

	protected $kategori;
	protected $subKategori;

	public function __construct(KategoriRepository $kategori, SubKategoryRepository $subKategori)
	{
		$this->kategori = $kategori;
		$this->subKategori = $subKategori;
	}


    public function indexKategori()
    {
    	$kategori = $this->kategori->getData();
        $subKategori = $this->subKategori->getData();

        return view('backend.master-data.index', compact('kategori','subKategori'));
    }

    public function storeKategori(Request $request)
    {
        $data = $request->all();
        $this->kategori->store($data);
        return redirect(route('admin.master-data.'));
    }

    public function storeSubKategori(Request $request)
    {
        $data = $request->all();
        $this->subKategori->store($data);
        return redirect(route('admin.master-data.'));
    }


    public function ajaxKategori(Request $request)
    {
        $search = $request->all() ?? [];
        $kategori =  $this->kategori->getData($search);
        foreach ($kategori as $key => $row) {
            $data[] = [
                'id' => $row->id,
                'text' => $row->nama_kategori
            ];
        }
        $datas = ['results' => $data];
        return response()->json($datas);
    }


}

app/Http/Controllers/backend/UserController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Repositories\RoleRepository;
use App\Http\Repositories\UserRepository;
use App\Role;
use App\User;

class UserController extends Controller
{

	protected $user;

	public function __construct(UserRepository $user)
	{
		$this->user = $user;
	}

    public function index()
    {
    	$users = $this->user->getData();
        return view('backend.user.index', compact('users'));
    }

    public function create()
    {
        $roles = $this->user->getRole();
        return view('backend.user.create', compact('roles'));
    }

    public function store(Request $request)
    {

        $user = new User();

        $data = $request->all();
        $user->name = $data['name'];
        $user->email = $data['email'];
        $user->password = $data['password'];
        $user->save();
        $user->roles()->attach($data['roles']);
        return redirect(route('admin.user'));
    }
}

resources/views/backend/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Your Application</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets') }}/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('assets') }}/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ asset('assets') }}/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('assets') }}/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('assets') }}/build/css/custom.min.css" rel="stylesheet">

        <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link href="{{ asset('assets') }}/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="{{ asset('assets') }}/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="{{ asset('assets') }}/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
    <link href="{{ asset('assets') }}/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <link href="{{ asset('assets') }}/vendors/switchery/dist/switchery.min.css" rel="stylesheet">

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Admin</span></a>
            </div>

            <div class="clearfix"></div>

            @include('backend.navigasi')
           
          </div>
        </div>

        @include('backend.top-nav')


        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">

            @yield('content')

          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>


      <!-- jQuery -->
    <script src="{{ asset('assets') }}/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('assets') }}/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets') }}/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="{{ asset('assets') }}/vendors/nprogress/nprogress.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('assets') }}/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="{{ asset('assets') }}/vendors/iCheck/icheck.min.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('assets') }}/vendors/moment/min/moment.min.js"></script>
    <script src="{{ asset('assets') }}/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap-wysiwyg -->
    <script src="{{ asset('assets') }}/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
    <script src="{{ asset('assets') }}/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
    <script src="{{ asset('assets') }}/vendors/google-code-prettify/src/prettify.js"></script>
    <!-- jQuery Tags Input -->
    <script src="{{ asset('assets') }}/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
    <!-- Switchery -->
    <script src="{{ asset('assets') }}/vendors/switchery/dist/switchery.min.js"></script>
    <!-- Parsley -->
    <script src="{{ asset('assets') }}/vendors/parsleyjs/dist/parsley.min.js"></script>
    <!-- Autosize -->
    <script src="{{ asset('assets') }}/vendors/autosize/dist/autosize.min.js"></script>
    <!-- jQuery autocomplete -->
    <script src="{{ asset('assets') }}/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
    <!-- starrr -->
    <script src="{{ asset('assets') }}/vendors/starrr/dist/starrr.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="{{ asset('assets') }}/build/js/custom.min.js"></script>
    

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  </body>
</html>

resources/views/backend/navigasi.blade.php
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="images/img.jpg" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2>John Doe</h2>
  </div>
</div>

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{{ route('admin.dashboard') }}">list Data</a></li>
          <li><a href="{{ route('admin.data.create') }}">Tambah Data</a></li>
        </ul>
      </li>

       <li><a href="{{ route('admin.master-data.') }}"><i class="fa fa-cog"></i> Master Data </span></a></li>
      
      <li><a><i class="fa fa-users"></i> User <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{{ route('admin.user.list') }}">Data List</a></li>
          <li><a href="{{ route('admin.user.create') }}">Tambah</a></li>
        </ul>
      </li>

      <li><a><i class="fa fa-cogs"></i> Permission <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{{ route('admin.role.list') }}">Data List</a></li>
          <li><a href="{{ route('admin.role.create') }}">Tambah</a></li>
        </ul>
      </li>

    </ul>
  </div>

</div>
<!-- /sidebar menu -->

resources/views/backend/top-nav.blade.php
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="images/img.jpg" alt="">John Doe
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->