routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'login', 'middleware' => 'guest', 'uses' => '\App\Http\Controllers\HomeController@index']);
Route::post('/do-login', ['as' => 'do-login', 'uses' => '\App\Http\Controllers\HomeController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => '\App\Http\Controllers\HomeController@logout']);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {

    Route::get('/', ['as' => 'dashboard', 'uses' => '\App\Http\Controllers\backend\DashboardController@index']);

    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/list', ['as' => 'list', 'uses' => '\App\Http\Controllers\backend\UserController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => '\App\Http\Controllers\backend\UserController@store']);
    });

    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/list', ['as' => 'list', 'uses' => '\App\Http\Controllers\backend\RoleController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\RoleController@create']);
    });

    Route::group(['prefix' => 'master-data', 'as' => 'master-data.'], function () {
        Route::get('/', ['uses' => '\App\Http\Controllers\backend\MasterDataController@indexKategori']);
        Route::get('/ajax-category', ['as' => 'ajax-category' , 'uses' => '\App\Http\Controllers\backend\MasterDataController@ajaxKategori']);
        Route::post('/store-kategori', ['as' => 'store-kategori', 'uses' => '\App\Http\Controllers\backend\MasterDataController@storeKategori']);
        Route::post('/store-sub-kategori', ['as' => 'store-sub-kategori', 'uses' => '\App\Http\Controllers\backend\MasterDataController@storeSubKategori']);

    });

      Route::group(['prefix' => 'data', 'as' => 'data.'], function () {
        Route::get('/create', ['as' => 'create', 'uses' => '\App\Http\Controllers\backend\DashboardController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => '\App\Http\Controllers\backend\DashboardController@store']);

    });

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }


}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Repositories\KategoriRepository;
use App\Http\Repositories\TidRepository;
use App\Http\Repositories\SubKategoryRepository;
use Illuminate\Http\Request;
use Auth;

class DashboardController extends Controller
{

	protected $kategori;

	protected $subKategori;

    protected $tid;

	public function __construct(KategoriRepository $kategori, SubKategoryRepository $subKategori, TidRepository $tid)
	{
		$this->kategori = $kategori;
		$this->subKategori = $subKategori;
        $this->tid = $tid;

	}


    public function index(Request $request)
    {
        $data = $request->all();
    	$subKategoris = $this->subKategori->getData();
        $checklist = $this->tid->getData($data);
        return view('backend.data.index', compact('subKategoris','checklist'));
    }


    public function create()
    {

        $tid = $this->createTID();
    	$subKategoris = $this->subKategori->getData();
        return view('backend.data.create', compact('subKategoris','tid'));
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $dataTid = array('tid_id' => $data['tid'], 'id_user' => Auth::user()->id, 'keterangan' => $data['keterangan']);
        $tid =  $this->tid->store($dataTid);
        $subKategoris = $this->subKategori->getData();
        foreach($subKategoris as $i => $row) { 
            $a = array_search($row->id, $data['id_sub_kategori'] ?? []);
            if ( ( $data['id_sub_kategori'][$a] ?? '' ) == $row->id ) {
                $data_checklist[] = array(
                        'id_sub_kategori' =>  $row->id ,
                        'status' => 1, 
                        'id_tid' => $tid->id,
                        'kode_tid' => $data['tid']
                       
                    ); 
            }else{
                $data_checklist[] = array(
                        'id_sub_kategori' =>  $row->id ,
                        'status' => 0, 
                        'id_tid' => $tid->id,
                        'kode_tid' => $data['tid'],
                    );
            }
        }

        $tid->checklist()->createMany($data_checklist);
        return redirect(route('admin.dashboard'));
    }


    public function createTID()
    {
         $userId = Auth::user()->id;
         return $tid = 'PID-'.$userId.'-'.date('dmis');
    }
}

app/Http/Controllers/backend/MasterDataController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Repositories\KategoriRepository;
use App\Http\Repositories\SubKategoryRepository;
use Illuminate\Http\Request;

class MasterDataController extends Controller
{

	protected $kategori;
	protected $subKategori;

	public function __construct(KategoriRepository $kategori, SubKategoryRepository $subKategori)
	{
		$this->kategori = $kategori;
		$this->subKategori = $subKategori;
	}


    public function indexKategori()
    {
    	$kategori = $this->kategori->getData();
        $subKategori = $this->subKategori->getData();

        return view('backend.master-data.index', compact('kategori','subKategori'));
    }

    public function storeKategori(Request $request)
    {
        $data = $request->all();
        $this->kategori->store($data);
        return redirect(route('admin.master-data.'));
    }

    public function storeSubKategori(Request $request)
    {
        $data = $request->all();
        $this->subKategori->store($data);
        return redirect(route('admin.master-data.'));
    }


    public function ajaxKategori(Request $request)
    {
        $search = $request->all() ?? [];
        $kategori =  $this->kategori->getData($search);
        foreach ($kategori as $key => $row) {
            $data[] = [
                'id' => $row->id,
                'text' => $row->nama_kategori
            ];
        }
        $datas = ['results' => $data];
        return response()->json($datas);
    }


}

app/Http/Controllers/backend/UserController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Repositories\RoleRepository;
use App\Http\Repositories\UserRepository;
use App\Role;
use App\User;

class UserController extends Controller
{

	protected $user;

	public function __construct(UserRepository $user)
	{
		$this->user = $user;
	}

    public function index()
    {
    	$users = $this->user->getData();
        return view('backend.user.index', compact('users'));
    }

    public function create()
    {
        $roles = $this->user->getRole();
        return view('backend.user.create', compact('roles'));
    }

    public function store(Request $request)
    {

        $user = new User();

        $data = $request->all();
        $user->name = $data['name'];
        $user->email = $data['email'];
        $user->password = $data['password'];
        $user->save();
        $user->roles()->attach($data['roles']);
        return redirect(route('admin.user'));
    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layout')

@section('content')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Form</h2>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<br />

				{{ Form::open(array('url' => route('admin.user.store'), 'method' => 'post', 'class' => 'form-horizontal form-label-left')) }}
					<div class="form-group">
						<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Name <span class="required">*</span>
						</label>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="name">
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
						</label>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<input type="email" id="email" required="required" class="form-control col-md-7 col-xs-12" name="email">
						</div>
					</div>


					<div class="form-group">
						<label class="control-label col-md-3 col-sm-3 col-xs-12" for="role">Role <span class="required">*</span>
						</label>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<select class="form-control col-md-7 col-xs-12" required="" name="roles">
								<option value="" selected="">Pilih Role</option>
								@foreach($roles as $role)
								<option value="{{ $role->id }}">{{ $role->name }}</option>
								@endforeach
							</select>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">password <span class="required">*</span>
						</label>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<input type="password" id="password" required="required" class="form-control col-md-7 col-xs-12" name="password">
						</div>
					</div>
					
					<div class="ln_solid"></div>
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							<button class="btn btn-primary" type="reset">Reset</button>
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>

				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>


@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layout')

@section('content')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Default Example <small>Users</small></h2>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<table id="datatable" class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Name</th>
							<th>Email</th>
							<th>Password</th>
							<th>Aksi</th>
						</tr>
					</thead>

					<tbody>
						@foreach($users as $user)
						<tr>
							<td>{{ $user->name }}</td>
							<td>{{ $user->email }}</td>
							<td>{{ $user->roles()->first()->name }}</td>
							<td>61</td>
						</tr>
						@endforeach
						
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>
@endsection